# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr: none

pool:
  vmImage: windows-latest

steps:
- task: OneLocBuild@1
  inputs:
    locProj: 'Jeeyyoo-Test-Folder/Localize/LocProject.json'
    outDir: '$(Build.ArtifactStagingDirectory)'
    isCreatePrSelected: true
    repoType: 'gitHub'
    prSourceBranchPrefix: 'locfiles'
    gitHubPatVariable: '$(GitHubPat)'
    isDeletePrSourceBranchSelected: false
    gitHubPrMergeMethod: 'squash'
    packageSourceAuth: 'patAuth'
    patVariable: '$(OneLocBuildPat)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'