### YamlMime:Episode
entryId: 76c1dde1-36be-4a49-8ee2-6088f0273659
showId: iot
uid: applied-nested-edge-in-an-industrial-environment
title: "Applied Nested Edge in an industrial environment"
description: |
  <p>Learn how to apply a hierarchy of nested Edge devices at scale to an ISA-95 industrial network using best practices and Azure IoT services. Watch a short demo using a physical 3-tier gateway setup showcasing how to address, control and manage the different layers of the Nested Edge environment through the cloud, how to deploy a configuration to deployed devices and what happens if a device loses network connection.</p>
  <p>Stefanie's Introduction <a href="#time=1m1s">[01:01]</a></p>
  <p>Philip's Introduction <a href="#time=1m34s">[01:34]</a></p>
  <p>Consumer IoT vs Industrial IoT <a href="#time=2m50s">[02:50]</a></p>
  <p>Philip's Presentation <a href="#time=9m07s">[09:07]</a></p>
  <p>Learn more reading the blog post at <a href="https://aka.ms/iotshow/NestedEdgeInIIoT" target="_blank">https://aka.ms/iotshow/NestedEdgeInIIoT</a></p><div class="ms-editor-squiggler">&nbsp;</div>
creators:
- Olivier Bloch
- Stefanie Grois
- Philip Derbyshire
uploadDate: "2021-04-28T16:00:00.000Z"
